name: SIGMA release with maven use graal VM.

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: SIGMA on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Setup jdk.
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: maven

      - name: Build with Maven.
        run: mvn -Pnative -DskipTests package

      - name: Tar package on Unix.
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          tar -zvcf ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tar.gz ./bin/sigma* ./options.json ./sigma.json

      - name: Zip package on windows.
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          7z a ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.zip ./bin/sigma* ./options.json ./sigma.json

      - name: Upload package.
        uses: actions/upload-artifact@v4
        with:
          name: sigma-${{ matrix.os }}
          path: |
            ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tar.gz
            ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.zip

      - name: Create release.
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
          files: |
            ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.tar.gz
            ./bin/sigma_${{ github.ref_name }}_${{ runner.os }}_${{ runner.arch }}.zip
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GH_TOKEN }}